### Copyright (c) 2021 Advanced Micro Devices, Inc. All rights reserved. ###

#-----------------------------------------------------------------------
# Common LZ4 Implementation Files
#-----------------------------------------------------------------------

vpath %.c $(PAL_LZ4_DEPTH)

CFILES += lz4.c      \
          lz4frame.c \
          lz4hc.c    \
          xxhash.c

#-----------------------------------------------------------------------
# Common LZ4 Includes and Definitions
#-----------------------------------------------------------------------

LCINCS   += -I$(PAL_LZ4_DEPTH)
LCDEFS   += -DLZ4_HC_STATIC_LINKING_ONLY

LCXXINCS += -I$(PAL_LZ4_DEPTH)
LCXXDEFS += -DLZ4_HC_STATIC_LINKING_ONLY
