####
#
#   Makefile for building MetroHash
#
####

#-----------------------------------------------------------------------
# Common MetroHash Implementation Files
#-----------------------------------------------------------------------

vpath %.cpp $(METROHASH_DEPTH)/src

CPPFILES += metrohash64.cpp     \
            metrohash128.cpp

#-----------------------------------------------------------------------
# Common MetroHash Includes
#-----------------------------------------------------------------------

LCXXINCS += -I$(METROHASH_DEPTH)/src
